---
title: 'RMarkdown:  In Class Assignment'
author: "Esmay Muniz"
date: "Data 2401"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) ## this line makes all the code show! 
  ## and these lines are comments - anything behind a '#' doesn't run!
```


Reminder: There is a "Markdown Help" page available in RStudio. 


## In-class Activity, Markdown

Below the "Your work here" section header, do the following 3 things. To turn this in, knit the RMarkdown file, and zip and submit the html.  

1. Make a subsection called "Wise words". Put your favorite quote in a block quote. Add a functioning link to a website that provides more information about that quote.

2. Make a subsection called "My semester". Make a three column table of the current courses you are taking, with separate columns for course number (put those in __bold__), course title (put those in _italics_), and instructor name.

3. Lastly, make subsection called "I recommend", and add some information about your favorite author or musician.

+ A _subsubheading_ with the name of the artist or author;    
+ An example of their writing or lyrics (formatted in a *plain code block*);   
+ A _list_ of things they have written or performed (remember to use the formatting markup for a list!).     


Note that you can click "Knit" as you go along to see what the final results are going to look like. **Once you're done, commit the changes and push the repo back to your assignment on GitHub!**

# My work here

## Wisewords

>*if it's not me, then who*

[link] (https://www.goodreads.com/author/quotes/637379.Dean_Graziosi)

# My semester

|Course Number|Course Title|Instructor name|
|:------------|:-----------|:--------------|
|__2401__     |_Data Science_|Shoemaker    |
|__4310__     |_Stats Computing_      |Mhoon      |
|__4397__     |_Stat Regression Analysis with R_  |Nguyen       |


## I recommend
-shifting Latino's norms
-Big icon in the Latino community
-unapologetic for who he is, no matter his status
-Makes great music


## Bad Bunny

>*a good song never gets old*

+ Artist of the year 2022
+ titi me pregunto
+ ojitos lindos

 
 
